In [13]:
import numpy as np
array1=np.array(range(30))
list1=array1.reshape(5,6,order="F")
print(list1)
np.where(list1%6==1)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))